SET ANSI_PADDING ON
GO

/****** Object:  Index [idx_GuiasHouse_idCliente]    Script Date: 2/5/2026 5:44:42 PM ******/
CREATE NONCLUSTERED INDEX [idx_GuiasHouse_BilltoConsigneeId] ON [dbo].[GuiasHouse]
(
	[BilltoConsigneeId] ASC,
	[ConsigneeId] ASC
)
INCLUDE([id]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 50, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


